name: rive_workshop
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rive: 0.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  countup: 0.1.4


flutter:
  uses-material-design: true


  assets:
    - assets/animation/rive_workshop_speedo.riv
